FROM python:3.5.2-alpine
COPY . /app
WORKDIR /app


# install dependencies
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
RUN python3 -m pip install numpy
RUN python3 -m pip install pandas
EXPOSE 5000 

# command to run on container start
ENTRYPOINT [ "python" ] 
CMD [ "app.py" ]